name: weather_app
description: A Weather App Project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  device_preview_plus: ^2.2.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1 
  flutter_riverpod: ^2.6.1 
  flutter_svg: ^2.0.17
  geolocator: ^13.0.2 
  http: ^1.3.0 
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  custom_lint: 

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launcher.png"